```{r, include = FALSE}
ottr::set_knitr_image_path()
```
# Terra overview

Let's begin with a short introductory video about Terra. After watching this video, you should understand Terra's mission and be familiar with its core functionality.

You'll see that the video is presented as a "video assignment." (And you'll similarly see reading assignments just a little later). To move smoothly through the course, watch or read each assigned resource before moving on. We should point out that although our articles routinely link readers to further resources and more detailed articles for those who want to learn more, we don't expect that you will do so in this course. Reading just the assigned article is sufficient. (Though if you are curious and want to keep reading, please do!).

Video assignment (2 minutes 39 seconds):

[Terra in a nutshell](https://youtu.be/w9mGcvU65r0)

After viewing the video, ask yourself: 
- What is the advantage of a cloud-centric approach to data sharing?
- How does Terra help facilitate data analysis for biomedical researchers?
- For which biomedical research communities does Terra serve as a hub?

Next is some reading to supplement what you just watched. The following article describes more about Terra's functionality, particularly the types of analysis you can do -- without going too deep into configurations and other details just yet.

Reading assignment (7 minute read): [Biomedical research in the cloud on Terra](https://support.terra.bio/hc/en-us/articles/360022714931)

While reading the article, ask yourself:
- What kinds of analyses can I do in Terra?
- Which types of analysis are suited for pipelining with workflows?
- Which interactive analysis tools can I run in Terra?

## New to cloud

If you are new to the cloud entirely, making the transition from your local computing environment to Terra might seem daunting. But it doesn’t need to be. For this introductory course we won’t take you on a deep-dive into cloud computing, but you will need to be aware of some core concepts. This will help you understand the architecture of Terra in the section following this one. 

Reading assignment (3 minute read): [New to Cloud](https://terra.bio/resources/new-to-cloud/)

While reading this brief overview on the Terra website, ask yourself:
- Where are files stored in the cloud?
- How are computing resources and software organized in the cloud?
- How do I pay for cloud computing expenses?
- How is access to resources and spending controlled?
- What are some important considerations for storing data in the cloud?

## Terra and data in the cloud

After that high-level introduction to the cloud in the previous section, let’s now look more into Terra's relationship with data, and how it is different from working in an institutional high-performance computing environment or other local analysis platform. For example, where exactly is data stored? How do you access, organize, and interact with data in Terra? How do you find data libraries from which to import data to Terra? In the assigned reading, you'll learn how cloud storage and the Terra Cloud Environment integrate with the Terra workspace and how your files live across different resources. 

Reading assignment (7 minute read): [Terra architecture and how your files live in it](https://support.terra.bio/hc/en-us/articles/360058163311)

While reading the article, ask yourself:
- What are the basic components of Terra?
- Where can data be stored?
- What are the basic components of the Terra Cloud Environment?
- How do cloud resources communicate so that I can move files between them?

If there are any cloud terminology terms you come across that you aren’t familiar with, you can refer to our [glossary of terms related to cloud-based genomics](https://support.terra.bio/hc/en-us/articles/4402431295245).
